services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Hyperdigital\HdTranslator\:
    resource: '../Classes/*'

  Hyperdigital\HdTranslator\Hooks\DocHeaderButtonsHook:
    tags:
      - name: event.listener
        identifier: 'hd-translator/hooks/modify-button-bar'
        method: 'modifyButtonBarColumns'
      - name: event.listener
        identifier: 'hd-translator/recordlist/my-event-listener'
        method: 'modifyRecordActions'

  Hyperdigital\HdTranslator\ContextMenu\ExportItemProvider:
    tags:
      - name: backend.contextmenu.itemprovider

