services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Hyperdigital\HdTranslator\:
    resource: '../Classes/*'

  Hyperdigital\HdTranslator\Hooks\DocHeaderButtonsHook:
    tags:
      - name: event.listener
        identifier: 'hd-translator/hooks/modify-button-bar'
